nohup /home/zhiyu/anaconda3/envs/GPU/bin/python3.6 -u PGD_test.py -dataset mnist -model leNet_1 -fitness nc >> /media/data1/DeepSuite/PGD_DeepXplore/log/leNet_1_nc.log 2>&1 &
nohup /home/zhiyu/anaconda3/envs/GPU/bin/python3.6 -u PGD_test.py -dataset mnist -model leNet_1 -fitness kmnc >> /media/data1/DeepSuite/PGD_DeepXplore/log/leNet_1_nc.log 2>&1 &
nohup /home/zhiyu/anaconda3/envs/GPU/bin/python3.6 -u PGD_test.py -dataset mnist -model leNet_1 -fitness nbc >> /media/data1/DeepSuite/PGD_DeepXplore/log/leNet_1_nc.log 2>&1 &
nohup /home/zhiyu/anaconda3/envs/GPU/bin/python3.6 -u PGD_test.py -dataset mnist -model leNet_1 -fitness snac >> /media/data1/DeepSuite/PGD_DeepXplore/log/leNet_1_nc.log 2>&1 &
nohup /home/zhiyu/anaconda3/envs/GPU/bin/python3.6 -u PGD_test.py -dataset mnist -model leNet_1 -fitness tknc >> /media/data1/DeepSuite/PGD_DeepXplore/log/leNet_1_nc.log 2>&1 &
nohup /home/zhiyu/anaconda3/envs/GPU/bin/python3.6 -u PGD_test.py -dataset mnist -model leNet_4 -fitness nc >> /media/data1/DeepSuite/PGD_DeepXplore/log/leNet_4_nc.log 2>&1 &
nohup /home/zhiyu/anaconda3/envs/GPU/bin/python3.6 -u PGD_test.py -dataset mnist -model leNet_4 -fitness kmnc >> /media/data1/DeepSuite/PGD_DeepXplore/log/leNet_4_nc.log 2>&1 &
nohup /home/zhiyu/anaconda3/envs/GPU/bin/python3.6 -u PGD_test.py -dataset mnist -model leNet_4 -fitness nbc >> /media/data1/DeepSuite/PGD_DeepXplore/log/leNet_4_nc.log 2>&1 &
nohup /home/zhiyu/anaconda3/envs/GPU/bin/python3.6 -u PGD_test.py -dataset mnist -model leNet_4 -fitness snac >> /media/data1/DeepSuite/PGD_DeepXplore/log/leNet_4_nc.log 2>&1 &
nohup /home/zhiyu/anaconda3/envs/GPU/bin/python3.6 -u PGD_test.py -dataset mnist -model leNet_4 -fitness tknc >> /media/data1/DeepSuite/PGD_DeepXplore/log/leNet_4_nc.log 2>&1 &
nohup /home/zhiyu/anaconda3/envs/GPU/bin/python3.6 -u PGD_test.py -dataset mnist -model leNet_5 -fitness nc >> /media/data1/DeepSuite/PGD_DeepXplore/log/leNet_5_nc.log 2>&1 &
nohup /home/zhiyu/anaconda3/envs/GPU/bin/python3.6 -u PGD_test.py -dataset mnist -model leNet_5 -fitness kmnc >> /media/data1/DeepSuite/PGD_DeepXplore/log/leNet_5_nc.log 2>&1 &
nohup /home/zhiyu/anaconda3/envs/GPU/bin/python3.6 -u PGD_test.py -dataset mnist -model leNet_5 -fitness nbc >> /media/data1/DeepSuite/PGD_DeepXplore/log/leNet_5_nc.log 2>&1 &
nohup /home/zhiyu/anaconda3/envs/GPU/bin/python3.6 -u PGD_test.py -dataset mnist -model leNet_5 -fitness snac >> /media/data1/DeepSuite/PGD_DeepXplore/log/leNet_5_nc.log 2>&1 &
nohup /home/zhiyu/anaconda3/envs/GPU/bin/python3.6 -u PGD_test.py -dataset mnist -model leNet_5 -fitness tknc >> /media/data1/DeepSuite/PGD_DeepXplore/log/leNet_5_nc.log 2>&1 &
