#python diversity.py -dataset SVHN -model vgg19 --num_div 1 --each_div 1000
#python diversity.py -dataset SVHN -model vgg19 --num_div 2 --each_div 500
#python diversity.py -dataset SVHN -model vgg19 --num_div 3 --each_div 333
#python diversity.py -dataset SVHN -model vgg19 --num_div 4 --each_div 250
#python diversity.py -dataset SVHN -model vgg19 --num_div 5 --each_div 200
#python diversity.py -dataset SVHN -model vgg19 --num_div 6 --each_div 166
#python diversity.py -dataset SVHN -model vgg19 --num_div 7 --each_div 142
#python diversity.py -dataset SVHN -model vgg19 --num_div 8 --each_div 125
#python diversity.py -dataset SVHN -model vgg19 --num_div 9 --each_div 111
#python diversity.py -dataset SVHN -model vgg19 --num_div 10 --each_div 100
#
#python diversity.py -dataset SVHN -model resnet34 --num_div 1 --each_div 1000
python diversity.py -dataset SVHN -model resnet34 --num_div 2 --each_div 500
python diversity.py -dataset SVHN -model resnet34 --num_div 3 --each_div 333
python diversity.py -dataset SVHN -model resnet34 --num_div 4 --each_div 250
python diversity.py -dataset SVHN -model resnet34 --num_div 5 --each_div 200
python diversity.py -dataset SVHN -model resnet34 --num_div 6 --each_div 166
python diversity.py -dataset SVHN -model resnet34 --num_div 7 --each_div 142
python diversity.py -dataset SVHN -model resnet34 --num_div 8 --each_div 125
python diversity.py -dataset SVHN -model resnet34 --num_div 9 --each_div 111
python diversity.py -dataset SVHN -model resnet34 --num_div 10 --each_div 100

python diversity.py -dataset SVHN -model WRN --num_div 1 --each_div 1000
python diversity.py -dataset SVHN -model WRN --num_div 2 --each_div 500
python diversity.py -dataset SVHN -model WRN --num_div 3 --each_div 333
python diversity.py -dataset SVHN -model WRN --num_div 4 --each_div 250
python diversity.py -dataset SVHN -model WRN --num_div 5 --each_div 200
python diversity.py -dataset SVHN -model WRN --num_div 6 --each_div 166
python diversity.py -dataset SVHN -model WRN --num_div 7 --each_div 142
python diversity.py -dataset SVHN -model WRN --num_div 8 --each_div 125
python diversity.py -dataset SVHN -model WRN --num_div 9 --each_div 111
python diversity.py -dataset SVHN -model WRN --num_div 10 --each_div 100