python ood_loader.py -dataset mnist -model leNet_1 -fitness nc
python ood_loader.py -dataset mnist -model leNet_1 -fitness kmnc
python ood_loader.py -dataset mnist -model leNet_1 -fitness nbc
python ood_loader.py -dataset mnist -model leNet_1 -fitness snac
python ood_loader.py -dataset mnist -model leNet_1 -fitness tknc
python ood_loader.py -dataset mnist -model leNet_1 -fitness idc
python ood_loader.py -dataset mnist -model leNet_4 -fitness nc
python ood_loader.py -dataset mnist -model leNet_4 -fitness kmnc
python ood_loader.py -dataset mnist -model leNet_4 -fitness nbc
python ood_loader.py -dataset mnist -model leNet_4 -fitness snac
python ood_loader.py -dataset mnist -model leNet_4 -fitness tknc
python ood_loader.py -dataset mnist -model leNet_4 -fitness idc
python ood_loader.py -dataset mnist -model leNet_5 -fitness nc
python ood_loader.py -dataset mnist -model leNet_5 -fitness kmnc
python ood_loader.py -dataset mnist -model leNet_5 -fitness nbc
python ood_loader.py -dataset mnist -model leNet_5 -fitness snac
python ood_loader.py -dataset mnist -model leNet_5 -fitness tknc
python ood_loader.py -dataset mnist -model leNet_5 -fitness idc